name: workflow-fork
on: push
jobs:
  print:
  runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Print Hello from Hexlet
        uses: hexlet-components/hello-from-hexlet-action@release