name: workflow-fork
on: push
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: make setup
      - run: make test
      - run: make lint